export const routes = {
    accordionPage: "/accordion",
    alertsPage: "/alerts",
    animationsPage: "/animations",
    articlePage: "/article",
    buttonsPage: "/buttons",
    columnsPage: "/columns",
    formsPage: "/forms",
    heroPage: "/hero",
    homePage: "/",
    loadersPage: "/loaders",
    menusPage: "/menus",
    messagesPage: "/messages",
    progressPage: "/progress",
    segmentsPage: "/segments",
    slideshowPage: "/slideshow",
    tablesPage: "/tables",
    tooltipPage: "/tooltip",
    typographyPage: "/typography"
};